In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

In [6]:
model_df = pd.read_csv('model.csv', index_col='AssignedID')
data = pd.read_csv('data.csv', index_col='AssignedID')

In [7]:
model_df

,StateCluster_0,StateCluster_2,StateCluster_3,StateCluster_4,StateCluster_5,StateCluster_6,StateCluster_7,MinPer,PropType_Dem_PUD,PropType_Hi-Rise_Condo,...,CoBoCreditScore_Not_Given,CoBoCreditScore_Poor,Term,AmorTerm,Rate,Amount,Front,Back,PMI,Purpose
AssignedID,,,,,,,,,,,,,,,,,,,,,
2131406,1,0,0,0,0,0,0,29.85,0,0,...,0,0,360,360,0.0400,464782,0.2424,0.3221,0.0,1
2131407,1,0,0,0,0,0,0,67.24,0,0,...,0,0,360,360,0.0375,495000,0.2384,0.4550,0.0,1
2131408,1,0,0,0,0,0,0,40.76,0,0,...,0,0,360,360,0.0388,665287,0.1369,0.2102,0.0,2
2131409,1,0,0,0,0,0,0,75.97,0,0,...,1,0,360,360,0.0375,490320,0.2582,0.2951,0.0,1
2131410,1,0,0,0,0,0,0,64.56,0,0,...,1,0,360,360,0.0375,97206,0.4012,0.5304,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2161350,1,0,0,0,0,0,0,22.82,0,0,...,0,0,360,360,0.0525,195865,0.3263,0.4912,0.0,1
2161351,1,0,0,0,0,0,0,7.61,0,0,...,0,0,180,180,0.0438,296000,0.2250,0.3657,0.0,1
2161352,1,0,0,0,0,0,0,3.69,0,0,...,1,0,360,360,0.0475,66400,0.1089,0.2918,0.0,2
2161353,1,0,0,0,0,0,0,10.16,0,0,...,0,0,360,360,0.0500,245600,0.2114,0.2701,0.0,1
2161354,1,0,0,0,0,0,0,9.02,0,0,...,0,0,240,240,0.0463,100000,0.1453,0.4085,0.0,1

In [10]:
import xgboost as xgb
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import confusion_matrix

In [11]:
model_df.Purpose.value_counts()

1    42982
2    22096
Name: Purpose, dtype: int64

In [12]:
# fit a classifier model 
X = model_df.drop(columns=['Purpose'])
y = model_df.Purpose

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= .30, random_state=31)

clf = xgb.XGBClassifier()
clf.fit(X_train, y_train)
training_preds = clf.predict(X_train)
val_preds = clf.predict(X_test)
training_accuracy = accuracy_score(y_train, training_preds)
val_accuracy = accuracy_score(y_test, val_preds)

print("Training Accuracy: {:.4}%".format(training_accuracy * 100))
print("Validation accuracy: {:.4}%".format(val_accuracy * 100))

Training Accuracy: 79.93%
Validation accuracy: 79.84%